### ISSUE TITLE
Support for Cassandra v2+ 

### ISSUE THREAD

**Issue by riotCode** [thobbs/phpcassa#142]
Update phpcassa package to support the lastest versions of Cassandra.

**Comment by jippi** [comment]
bump

**Comment by vintrax** [comment]
I would love support for Cassandra V2.x too. Soo... upvote! :+1:

**Comment by rskvazh** [comment]
+1

**Comment by songlin** [comment]
+1

**Comment by trK54Ylmz** [comment]
+1

**Comment by argakon** [comment]
+1

**Comment by avalanche123** [comment]
Hello folks, I'm happy to announce that the alpha release of the official DataStax PHP Driver for Apache Cassandra is now available.

Head over to the repo for more info - https://github.com/datastax/php-driver

Cheers!
