### ISSUE TITLE
use c extension

### ISSUE THREAD

**Issue by yuanjiong199** [thobbs/phpcassa#151]
If I use C extensions. Cassandra at the time of connection. PHP is also need to require_once the php files lib directory?
e.g:
lib/cassandra/Cassandra.php
lib/cassandra/Types.php
lib/phpcassa/Connection/Connection.php

**Comment by thobbs** [comment]
I suggest doing your imports like this: https://github.com/thobbs/phpcassa/blob/master/examples/basic.php#L17-L22

Once the C extension is compiled, you don't need to include anything special to use it.  Just make sure ``thrift_protocol.so`` is added to your php.ini file, as described in the README file.
